name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true

env:
  JAVA_VERSION: '17'
  JAVA_DISTRO: 'adopt'

jobs:
  precheck:
    name: Precheck
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.vars.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Version
        id: vars
        shell: bash
        run: |
          VERSION=${{ github.event.inputs.version }}
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git commit --all --allow-empty --message "Releasing version $VERSION"
          git tag --annotate --message "Releasing version $VERSION" $VERSION
          git push --tags origin master

  release:
    name: Release
    needs: [ precheck ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Publish package
        env:
          JRELEASER_NEXUS2_USERNAME: ${{ secrets.JRELEASER_NEXUS2_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD: ${{ secrets.JRELEASER_NEXUS2_PASSWORD }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 1001
          HOMEDIR="$HOME/.gnupg"
          echo 1002
          OSSRH_FILE="$HOME/ossrh-settings.xml.secret"
          echo 1003
          PASSPHRASE_FILE="$HOME/gpg.passphrase.secret"
          echo 1004
          killall -9 gpg-agent || echo not found
          echo 1005
          rm -rf "$HOMEDIR"
          echo 1006
          mkdir "$HOMEDIR"
          echo 1007
          chmod 700 "$HOMEDIR"
          echo 1008
          echo $JRELEASER_GPG_SECRET_KEY | base64 -d | gpg --homedir "$HOMEDIR" --batch --import -
          echo 1009
          rm -f "$OSSRH_FILE"
          echo 1010
          cat ./ossrh-settings.xml | sed "s/magic0/$JRELEASER_NEXUS2_USERNAME/g" | sed "s/magic1/$JRELEASER_NEXUS2_PASSWORD/g" > "$OSSRH_FILE"
          echo 1011
          rm -f "$PASSPHRASE_FILE"
          echo 1012
          echo $JRELEASER_GPG_PASSPHRASE > "$PASSPHRASE_FILE"
          echo 1013
          mvn -s "$OSSRH_FILE" -Prelease clean
          echo 1014
          mvn -s "$OSSRH_FILE" -Prelease deploy
          echo 1015
          rm -rf "$HOMEDIR"
          echo 1016
          rm -f "$OSSRH_FILE"
          echo 1017
          rm -f "$PASSPHRASE_FILE"
          echo 1018
